# Builds, tests the project with Gradle and uploads to Modrinth
name: Java CI

on:
  push:
    branches: [ 'master' ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Fabric requires Fabric 17
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build test
      - name: Query Version
        run: |
          echo "::set-output name=VERSION_NAME::$(${{github.workspace}}/gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')"
        id: fetch-version
      - name: Get Version
        run: |
          echo "version_name=${{steps.fetch-version.outputs.VERSION_NAME}}" >> $GITHUB_ENV
      - name: Upload GitHub Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Plugin Jar
          path: target/PAPIProxyBridge-Plugin-*.jar
